# Generated by Django 2.1 on 2018-11-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Введите контент статьи', max_length=2000, verbose_name='Контент')),
                ('pub_date', models.DateTimeField(blank=True, help_text='Дата публикации', null=True, verbose_name='Опубликовано')),
                ('source_link', models.CharField(help_text='Введите ссылку на источник', max_length=200, null=True, verbose_name='Ссылка')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию', max_length=50, verbose_name='Категория')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тэг', max_length=50, verbose_name='Тэг')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(help_text='Выберите категорию', to='blog.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(help_text='Выберите тэги', to='blog.Tag', verbose_name='Тэги'),
        ),
    ]
